###

# Requisição válida
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "forma",
    "marcadores": [
        {"local": "selva"},
        {"personagem": "leao"},
        {"acao": "sonhando"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

# forma,local=selva,personagem=leao,acao=sonhando latitude=-27,longitude=-48,altitude=80

###

# Requisição inválida: cabeçalho não menciona formato
POST http://localhost:5000/gravar
Accept: application/json

{
    "medida": "forma",
    "marcadores": [
        {"local": "selva"},
        {"personagem": "leao"},
        {"acao": "sonhando"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###

# Requisição inválida: JSON com formato errado
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "forma
    "marcadores": [
        {"local": "selva"},
        {"personagem": "leao"},
        {"acao": "sonhando}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]

###

# Requisição inválida: falta 'medida'
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "forma
    "marcadores": [
        {"local": "selva"},
        {"personagem": "leao"},
        {"acao": "sonhando"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###

# Requisição inválida: 'medida' com formato errado
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "forma"
    "marcadores": [
        {"local": "selva"},
        {"personagem": "leao"},
        {"acao": "sonhando"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###

# Requisição inválida: falta 'valores'
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "forma",
    "marcadores": [
        {"local": "selva"},
        {"personagem": "leao"},
        {"acao": "sonhando"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###

# Requisição inválida: 'valores' com formato errado
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "forma",
    "marcadores": [
        {"local": "selva"},
        {"personagem": "leao"},
        {"acao": "sonhando"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###

# Requisição inválida: lista 'valores' vazia
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "forma",
    "marcadores": [
        {"local": "selva"},
        {"personagem": "leao"},
        {"acao": "sonhando"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###

# Requisição válida
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "forma",
    "marcadores": [
        {"local": "selva"},
        {"personagem": "leao"},
        {"url": "https://github.com/boidacarapreta/arc20201"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###
